# make run_local_solve dir=configs/rubik name=rubik_astar_solve
components_prefix: "./rl-data/validation/rubik/components/moe_uniform"

params:
  env:
    _target_: carl.environment.gym_rubik.rubik_env.RubikEnv
    tokenizer:
      _target_: carl.environment.gym_rubik.tokenizer.RubikCubeTokenizer
      cut_distance: 20
      type_of_value_training: "regression"

subgoal_generator:
  _target_: carl.inference_components.policy.PolicyGeneratorWrapper
  policy:
    _target_: carl.inference_components.policy.TransformerPolicy
    policy_network_class:
      _target_: transformers.BertForSequenceClassification.from_pretrained
      _partial_: true
    path_to_policy_weights: "./rl-data/validation/rubik/components/moe_uniform/policy/checkpoint-763128"
    env: ${params.env}
    confidence_threshold: 0.85
  env: ${params.env}

value_function:
  _target_: carl.inference_components.value.TransformerValue
  value_network_class:
    _target_: transformers.BertForSequenceClassification.from_pretrained
    _partial_: true
  path_to_value_network_weights: "./rl-data/validation/rubik/components/moe_uniform/value/checkpoint-14504490"
  type_of_evaluation: "regression"
  noise_variance: 0.0
  env: ${params.env}

validator:
  _target_: carl.inference_components.validator.DummyValidator
  env: ${params.env}

algorithm:
  _target_: carl.algorithms.solve_instances.SolveInstances
  solver:
    _target_: carl.solver.subgoal_search.Solver
    max_nodes: 5000
    planner_class:
      _partial_: true
      _target_: carl.solver.planners.AstarPlanner
      depth_weight: 1.0
      value_weight: 20.0
    subgoal_generator: ${subgoal_generator}
    validator: ${validator}
    value_function: ${value_function}
  data_loader:
    _target_: carl.environment.instance_generator.BasicInstanceGenerator
    generator:
      _target_: carl.environment.instance_generator.GeneralIterableDataLoader
      path_to_folder_with_data: "./rl-data/validation/rubik/progress/shuffle_general"
    batch_size: 25
  result_logger:
    _target_: carl.utils.result_loggers.SubgoalSearchResultLogger
    custom_logger:
      _target_: carl.utils.loggers.NeptuneCaRLLogger
      name: "rubik_astar_solve"
      description: "astar/bestfs solve"
      project: "mtyrol/drop"
      tags: ["inner_eval", "rubik", "AStar", "solve", "shuffle_20"]
      log_parameters: True
    problem_to_solve: ${algorithm.problems_to_solve}
    budget_logs: [1, 2, 5, 10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 120, 140, 160, 180, 200, 250, 300, 350, 400, 450, 500, 600, 800, 1000, 1500, 2000, 3000, 4000, 5000]
  problems_to_solve: 100
  n_parallel_workers: 8

carl_workers:
  solve:
    algorithm._target_: carl.algorithms.solve_instances.SolveInstances

carl_grid:
  # AStar variants
  - algorithm.solver.planner_class._target_: [carl.planners.greedy.AstarPlanner]
    algorithm.solver.planner_class.depth_weight: [0.1, 0.2, 0.5, 1.0]
    algorithm.solver.planner_class.value_weight: [20.0]
    algorithm.result_logger.custom_logger.tags: [["rubik", "astar", "grid", "shuffle_20"]]
  # BestFS variants
  - algorithm.solver.planner_class._target_: [carl.planners.greedy.BestFSPlanner]
    algorithm.result_logger.custom_logger.tags: [["rubik", "bestfs", "grid", "shuffle_20"]]
