float32_matmul_precision: medium

environment:
  env:
    _target_: carl.environment.sokoban.env.SokobanEnv
    tokenizer:
      _target_: carl.environment.sokoban.tokenizer.SokobanTokenizer
      cut_distance: 150
      type_of_value_training: regression
      size_of_board:
        - 12
        - 12
      remove_border: False
    num_boxes: 4


algorithm:
  problems_to_solve: 1000
  _target_: carl.algorithms.solve_instances.SolveInstances
  dump_solved: True
  # solver class
  solver:
    _target_: carl.solver.subgoal_search.Solver
    # _target_: carl.solver.subgoal_search_batched.SubgoalSearchSolver # Comment this for the non-batched version
    # inference_batch_size: 384 # Comment this for the non-batched version
    max_nodes: 2000
    planner_class:
      _partial_: true
      _target_: carl.solver.planners.AdasubsPlanner
      generators_k_list: [1] # [8]

    # subgoal generator
    subgoal_generator:
      _target_: carl.inference_components.subgoal_generator.AdaptiveSubgoalGenerator
      env: ${environment.env}
      subgoal_generation_kwargs:
        min_new_tokens: 145
        early_stopping: True
        max_new_tokens: 145
        num_beams: 4
        num_return_sequences: 2
      generator_k_list: ${algorithm.solver.planner_class.generators_k_list}
      paths_to_generator_weights:
        # - "./validation/sokoban/components/full_data/generator/border/8/checkpoint-75856"
        # - "./validation/sokoban/components/full_data/generator/border/4/checkpoint-75856"
        - "./validation/sokoban/components/full_data/generator/border/1/checkpoint-151712"
      subgoal_generator_class:
        _target_: carl.inference_components.subgoal_generator.TransformerSubgoalGenerator
        _partial_: True
        generator_network_class:
          _target_: transformers.BartForConditionalGeneration.from_pretrained
          _partial_: True
    # validator
    validator:
      _target_: carl.inference_components.validator.BasicValidator
      inference_batch_size: 1
      env: ${environment.env}
      # conditional low level policy
      cllp:
        _target_: carl.inference_components.conditional_low_level_policy.TransformerConditionalLowLevelPolicy
        conditional_low_level_policy_class:
          _target_: transformers.BertForSequenceClassification.from_pretrained
          _partial_: True
        path_to_conditional_low_level_policy_weights: "./validation/sokoban/components/full_data/cllp/8/checkpoint-167585"
        env: ${environment.env}

    # value function
    value_function:
      _target_: carl.inference_components.value.TransformerValue
      value_network_class:
        _target_: transformers.BertForSequenceClassification.from_pretrained
        _partial_: True
      path_to_value_network_weights: "./validation/sokoban/components/full_data/value/checkpoint-1343100"
      type_of_evaluation: "regression"
      env: ${environment.env}

  # data loader class
  data_loader:
    _target_: carl.environment.instance_generator.BasicInstanceGenerator
    generator:
      _target_: carl.environment.instance_generator.GeneralIterableDataLoader
      path_to_folder_with_data: "./validation/sokoban/progress"
    batch_size: 256

  # result logger
  result_logger:
    _target_: carl.utils.result_loggers.SubgoalSearchResultLogger
    custom_logger:
      _target_: carl.utils.loggers.NeptuneCaRLLogger
      name: "solve_instances"
      description: "Solve instances with AdaSubS"
      project: "pmtest/subexit"
      tags: 
        - ""
      log_parameters: False
    problem_to_solve: ${algorithm.problems_to_solve}
    budget_logs:
      - 100
      - 200
      - 300
      - 400
      - 500
      - 600
      - 700
      - 800
      - 900
      - 1000
      - 2000
      - 3000
      - 4000
      - 5000
      - 10000
  n_jobs: 24


carl_workers:
  solve:
    algorithm._target_: carl.algorithms.solve_instances.SolveInstances


carl_grid:
  - algorithm.result_logger.custom_logger.tags: [["KSubS - k1 - arxiv - 4boxes"]]
    environment.env.num_boxes: [4]
    algorithm.data_loader.generator.path_to_folder_with_data: ['./validation/sokoban/progress/boards_1000_b4_gs100_c300_p0.1', './validation/sokoban/progress/boards_1000_b4_gs100_c300_p0.35', './validation/sokoban/progress/boards_1000_b4_gs100_c300_p0.6', './validation/sokoban/progress/boards_1000_b4_gs100_c300_p0.85', './validation/sokoban/progress/boards_1000_b4_gs25_c300_p0.1', './validation/sokoban/progress/boards_1000_b4_gs25_c300_p0.35', './validation/sokoban/progress/boards_1000_b4_gs25_c300_p0.6', './validation/sokoban/progress/boards_1000_b4_gs25_c300_p0.85']
  - algorithm.result_logger.custom_logger.tags: [["KSubS - k1 - arxiv - 5boxes"]]
    environment.env.num_boxes: [5]
    algorithm.data_loader.generator.path_to_folder_with_data: ['./validation/sokoban/progress/boards_1000_b5_gs100_c300_p0.1', './validation/sokoban/progress/boards_1000_b5_gs100_c300_p0.35', './validation/sokoban/progress/boards_1000_b5_gs100_c300_p0.6', './validation/sokoban/progress/boards_1000_b5_gs100_c300_p0.85', './validation/sokoban/progress/boards_1000_b5_gs25_c300_p0.1', './validation/sokoban/progress/boards_1000_b5_gs25_c300_p0.35', './validation/sokoban/progress/boards_1000_b5_gs25_c300_p0.6', './validation/sokoban/progress/boards_1000_b5_gs25_c300_p0.85']
  - algorithm.result_logger.custom_logger.tags: [["KSubS - k1 - arxiv - 6boxes"]]
    environment.env.num_boxes: [6]
    algorithm.data_loader.generator.path_to_folder_with_data: ['./validation/sokoban/progress/boards_1000_b6_gs100_c300_p0.1', './validation/sokoban/progress/boards_1000_b6_gs100_c300_p0.35', './validation/sokoban/progress/boards_1000_b6_gs100_c300_p0.6', './validation/sokoban/progress/boards_1000_b6_gs100_c300_p0.85', './validation/sokoban/progress/boards_1000_b6_gs25_c300_p0.1', './validation/sokoban/progress/boards_1000_b6_gs25_c300_p0.35', './validation/sokoban/progress/boards_1000_b6_gs25_c300_p0.6', './validation/sokoban/progress/boards_1000_b6_gs25_c300_p0.85']
  - algorithm.result_logger.custom_logger.tags: [["KSubS - k1 - arxiv - 7boxes"]]
    environment.env.num_boxes: [7]
    algorithm.data_loader.generator.path_to_folder_with_data: ['./validation/sokoban/progress/boards_1000_b7_gs100_c300_p0.1', './validation/sokoban/progress/boards_1000_b7_gs100_c300_p0.35', './validation/sokoban/progress/boards_1000_b7_gs100_c300_p0.6', './validation/sokoban/progress/boards_1000_b7_gs100_c300_p0.85', './validation/sokoban/progress/boards_1000_b7_gs25_c300_p0.1', './validation/sokoban/progress/boards_1000_b7_gs25_c300_p0.35', './validation/sokoban/progress/boards_1000_b7_gs25_c300_p0.6', './validation/sokoban/progress/boards_1000_b7_gs25_c300_p0.85']
  - algorithm.result_logger.custom_logger.tags: [["KSubS - k1 - arxiv - 8boxes"]]
    environment.env.num_boxes: [8]
    algorithm.data_loader.generator.path_to_folder_with_data: ['./validation/sokoban/progress/boards_1000_b8_gs100_c300_p0.1', './validation/sokoban/progress/boards_1000_b8_gs100_c300_p0.35', './validation/sokoban/progress/boards_1000_b8_gs100_c300_p0.6', './validation/sokoban/progress/boards_1000_b8_gs100_c300_p0.85', './validation/sokoban/progress/boards_1000_b8_gs25_c300_p0.1', './validation/sokoban/progress/boards_1000_b8_gs25_c300_p0.35', './validation/sokoban/progress/boards_1000_b8_gs25_c300_p0.6', './validation/sokoban/progress/boards_1000_b8_gs25_c300_p0.85']
  - algorithm.result_logger.custom_logger.tags: [["KSubS - k1 - arxiv - 9boxes"]]
    environment.env.num_boxes: [9]
    algorithm.data_loader.generator.path_to_folder_with_data: ['./validation/sokoban/progress/boards_1000_b9_gs100_c300_p0.1', './validation/sokoban/progress/boards_1000_b9_gs100_c300_p0.35', './validation/sokoban/progress/boards_1000_b9_gs100_c300_p0.6', './validation/sokoban/progress/boards_1000_b9_gs100_c300_p0.85', './validation/sokoban/progress/boards_1000_b9_gs25_c300_p0.1', './validation/sokoban/progress/boards_1000_b9_gs25_c300_p0.35', './validation/sokoban/progress/boards_1000_b9_gs25_c300_p0.6', './validation/sokoban/progress/boards_1000_b9_gs25_c300_p0.85']
  - algorithm.result_logger.custom_logger.tags: [["KSubS - k1 - arxiv - 10boxes"]]
    environment.env.num_boxes: [10]
    algorithm.data_loader.generator.path_to_folder_with_data: ['./validation/sokoban/progress/boards_1000_b10_gs100_c300_p0.1', './validation/sokoban/progress/boards_1000_b10_gs100_c300_p0.35', './validation/sokoban/progress/boards_1000_b10_gs100_c300_p0.6', './validation/sokoban/progress/boards_1000_b10_gs100_c300_p0.85', './validation/sokoban/progress/boards_1000_b10_gs25_c300_p0.1', './validation/sokoban/progress/boards_1000_b10_gs25_c300_p0.35', './validation/sokoban/progress/boards_1000_b10_gs25_c300_p0.6', './validation/sokoban/progress/boards_1000_b10_gs25_c300_p0.85']
