algorithm:
  # main algorithm
  _target_: carl.algorithms.training_loop.TrainingLoopHF

  # general algorithm parameters
  n_iterations: 1000
  problem_to_evaluate: 100 # IGNORED
  n_jobs: 30
  min_count_of_new_solved_boards_to_next_train_iteration: 0

  # this data is used pure evaluation
  eval_data_path: null
  eval_batch_size: 256
  evaluate_every: 2_000_000 # inf
  initialization_buffer_with_data_used_for_components_training: True
  limit_of_data_used_for_components_training: 200
  path_to_data_used_for_components_training: './rlloop_icml/sokoban/offline_data/10_10_4_enhanced'
  workdir_to_import_weights_and_experiences_from: null # './rlloop_icml/sokoban/online_gathered_trajectories/sad_osmosis_f2c1/0'
  solver:
    _target_: carl.solver.subgoal_search.Solver
    # _target_: carl.solver.subgoal_search_batched.SubgoalSearchSolver # Comment this for the non-batched version
    # inference_batch_size: 384 # Comment this for the non-batched version
    max_nodes: 500
    planner_class:
      _partial_: true
      _target_: carl.solver.planners.AdasubsPlanner
      generators_k_list: [1]

    # subgoal generator
    subgoal_generator:
      _target_: carl.inference_components.subgoal_generator.AdaptiveSubgoalGenerator
      env:
        _target_: carl.environment.sokoban.env.SokobanEnv
        tokenizer:
          _target_: carl.environment.sokoban.tokenizer.SokobanTokenizer
          cut_distance: None
          type_of_value_training: regression
          size_of_board:
            - 8
            - 8
          remove_border: True
        num_boxes: 4
      subgoal_generation_kwargs:
        min_new_tokens: 65
        early_stopping: True
        max_new_tokens: 65
        num_beams: 16
        num_return_sequences: 4
        # do_sample: True
        # top_k: 2
      generator_k_list: [1]
      paths_to_generator_weights:
        # - "./rlloop_icml/sokoban/components/n_200/generator/6/checkpoint-4292"
        # - "./rlloop_icml/sokoban/components/n_200/generator/4/checkpoint-3327"
        # - "./rlloop_icml/sokoban/components/n_200/generator/2/checkpoint-4281"
        - "./rlloop_icml/sokoban/components/n_200/generator/1/checkpoint-4214"
      subgoal_generator_class:
        _target_: carl.inference_components.subgoal_generator.TransformerSubgoalGenerator
        _partial_: True
        generator_class:
          _target_: transformers.BartForConditionalGeneration.from_pretrained
          _partial_: True
        training_module:
          _target_: carl.inference_components.component.TrainingModule
          trainer_class:
            _target_: hydra.utils.get_class
            path: transformers.Trainer
          trainer_args:
            _partial_: True
            _target_: transformers.TrainingArguments
            overwrite_output_dir: True
            evaluation_strategy: epoch
            per_device_train_batch_size: 256
            per_device_eval_batch_size: 256
            learning_rate: 0.0001 # algorithm.solver.subgoal_generator.subgoal_generator_class.training_module.trainer_args.learning_rate
            weight_decay: 0.000001 # 0.0001
            num_train_epochs: 2
            lr_scheduler_type: constant
            logging_strategy: epoch
            save_strategy: epoch
            save_total_limit: 1
            report_to: none
            warmup_steps: 0
            # max_steps: 10 # TODO: change
          metrics_for_component:
            _target_: carl.components.metrics.GeneratorMetricsHF
    # validator
    validator:
      _target_: carl.inference_components.validator.BasicValidator
      inference_batch_size: 384
      env_class:
        _target_: carl.environment.sokoban.env.SokobanEnv
        tokenizer:
          _target_: carl.environment.sokoban.tokenizer.SokobanTokenizer
          cut_distance: 50
          type_of_value_training: regression
          size_of_board:
            - 10
            - 10
        num_boxes: 4
        _partial_: True

      # conditional low level policy
      cllp:
        _target_: carl.inference_components.conditional_low_level_policy.TransformerConditionalLowLevelPolicy
        conditional_low_level_policy_class:
          _target_: transformers.BertForSequenceClassification.from_pretrained
          _partial_: True
        path_to_conditional_low_level_policy_weights: "./rlloop_icml/sokoban/components/n_200/cllp/6/checkpoint-952"
        env:
          _target_: carl.environment.sokoban.env.SokobanEnv
          tokenizer:
            _target_: carl.environment.sokoban.tokenizer.SokobanTokenizer
            cut_distance: 50
            type_of_value_training: regression
            size_of_board:
              - 10
              - 10
          num_boxes: 4
        training_module:
          _target_: carl.inference_components.component.TrainingModule
          trainer_class:
            _target_: hydra.utils.get_class
            path: transformers.Trainer
          trainer_args:
            _partial_: True
            _target_: transformers.TrainingArguments
            overwrite_output_dir: True
            evaluation_strategy: epoch
            per_device_train_batch_size: 256
            per_device_eval_batch_size: 256
            learning_rate: 0.0001
            weight_decay: 0.0001 # 0.000001
            num_train_epochs: 2
            lr_scheduler_type: constant
            logging_strategy: epoch
            save_strategy: epoch
            save_total_limit: 1
            load_best_model_at_end: True
            metric_for_best_model: eval_loss
            report_to: none
            warmup_steps: 0
            # max_steps: 10 # TODO: change
          metrics_for_component:
            _target_: carl.components.metrics.ConditionalLowLevelPolicyMetricsHF

    # value function
    value_function:
      _target_: carl.inference_components.value.TransformerValue
      value_network_class:
        _target_: transformers.BertForSequenceClassification.from_pretrained
        _partial_: True
      path_to_value_network_weights: "./rlloop_icml/sokoban/components/n_200/value/checkpoint-2636"
      type_of_evaluation: "regression"
      env:
        _target_: carl.environment.sokoban.env.SokobanEnv
        tokenizer:
          _target_: carl.environment.sokoban.tokenizer.SokobanTokenizer
          cut_distance: 50
          type_of_value_training: "regression"
          size_of_board:
            - 10
            - 10
        num_boxes: 4
      training_module:
        _target_: carl.inference_components.component.TrainingModule
        trainer_class:
          _target_: hydra.utils.get_class
          path: transformers.Trainer
        trainer_args:
          _partial_: True
          _target_: transformers.TrainingArguments
          overwrite_output_dir: True
          evaluation_strategy: epoch
          per_device_train_batch_size: 256
          per_device_eval_batch_size: 256
          learning_rate: 0.0001
          weight_decay: 0.0001
          num_train_epochs: 2
          lr_scheduler_type: constant
          logging_strategy: epoch
          save_strategy: epoch
          save_total_limit: 1
          load_best_model_at_end: True
          metric_for_best_model: eval_loss
          report_to: none
          warmup_steps: 0
          # max_steps: 5 # TODO: change
        metrics_for_component:
          _target_: carl.components.metrics.ValueMetricsHF
          type_of_evaluation: "regression"

  # result logger
  result_logger:
    _target_: carl.utils.result_loggers.SubgoalSearchResultLogger
    custom_logger:
      _target_: carl.utils.loggers.NeptuneCaRLLogger
      name: "rlloop_adasubs_sokoban_tests"
      description: ""
      project: "pmtest/subexit"
      tags: "multinode-rlloop-dev-workers" # "rlloop k-subs 200 sokoban10x10 with 2k trajectories, more epochs"
      log_parameters: True
    budget_logs:
      - 100
      - 200
      - 300
      - 500
      - 1000
      - 2000
      - 3000
      - 5000


  # environment; it is the same for all components
  env:
    _target_: carl.environment.sokoban.env.SokobanEnv
    tokenizer:
      _target_: carl.environment.sokoban.tokenizer.SokobanTokenizer
      cut_distance: 50
      type_of_value_training: regression
      size_of_board:
        - 10
        - 10
    num_boxes: 4

  # params for replay buffers
  replay_buffer_data_split: 0.1

  # params for instances generator
  # this data is used during collecting data for replay buffers
  generated_data_path: "./rlloop_icml/sokoban/online_data/10_10_4"

  instance_generator_batch_size: 10
  curriculum:
    # _target_: carl.solver.curriculum.SimpleScheduledCurriculum
    # scheduler_generators:
    #   5: 2
    #   10: 4
    #   13: 6


  # path to save the models:
  weights_dump_path: ""
  replay_buffer:
    _target_: carl.memory.replay_buffer.SimpleUniversalReplayBuffer
    generator_buffer:
      # 6:
      #   _target_: carl.memory.replay_buffer.SolvingPathGeneratorReplayBuffer
      #   max_size: 400000
      #   distance_range: [5, 6, 7]
      #   env:
      #     _target_: carl.environment.sokoban.env.SokobanEnv
      #     tokenizer:
      #       _target_: carl.environment.sokoban.tokenizer.SokobanTokenizer
      #       cut_distance: None
      #       type_of_value_training: regression
      #       size_of_board:
      #         - 8
      #         - 8
      #       remove_border: True
      #     num_boxes: 4
      # 4:
      #   _target_: carl.memory.replay_buffer.SolvingPathGeneratorReplayBuffer
      #   max_size: 400000
      #   distance_range: [3, 4, 5]
      #   env:
      #     _target_: carl.environment.sokoban.env.SokobanEnv
      #     tokenizer:
      #       _target_: carl.environment.sokoban.tokenizer.SokobanTokenizer
      #       cut_distance: None
      #       type_of_value_training: regression
      #       size_of_board:
      #         - 8
      #         - 8
      #       remove_border: True
      #     num_boxes: 4
      # 2:
      #   _target_: carl.memory.replay_buffer.SolvingPathGeneratorReplayBuffer
      #   max_size: 400000
      #   distance_range: [1, 2, 3]
      #   env:
      #     _target_: carl.environment.sokoban.env.SokobanEnv
      #     tokenizer:
      #       _target_: carl.environment.sokoban.tokenizer.SokobanTokenizer
      #       cut_distance: None
      #       type_of_value_training: regression
      #       size_of_board:
      #         - 8
      #         - 8
      #       remove_border: True
      #     num_boxes: 4
      1:
        _target_: carl.memory.replay_buffer.SolvingPathGeneratorReplayBuffer
        max_size: 50000
        xy_dropout_prob: 0.2
        distance_range: [1]
        env:
          _target_: carl.environment.sokoban.env.SokobanEnv
          tokenizer:
            _target_: carl.environment.sokoban.tokenizer.SokobanTokenizer
            cut_distance: None
            type_of_value_training: regression
            size_of_board:
              - 8
              - 8
            remove_border: True
          num_boxes: 4
    value_buffer:
      _target_: carl.memory.replay_buffer.SolvingPathValueReplayBuffer
      max_size: 100000
      xy_dropout_prob: 0.2
      env:
        _target_: carl.environment.sokoban.env.SokobanEnv
        tokenizer:
          _target_: carl.environment.sokoban.tokenizer.SokobanTokenizer
          cut_distance: 50
          type_of_value_training: regression
          size_of_board:
            - 10
            - 10
        num_boxes: 4
    cllp_buffer:
      _target_: carl.memory.replay_buffer.SolvingPathConditionalLowLevelPolicyReplayBuffer
      max_size: 100000
      max_distance: 1
      xy_dropout_prob: 0.2
      env:
        _target_: carl.environment.sokoban.env.SokobanEnv
        tokenizer:
          _target_: carl.environment.sokoban.tokenizer.SokobanTokenizer
          cut_distance: 50
          type_of_value_training: regression
          size_of_board:
            - 10
            - 10
        num_boxes: 4

float32_matmul_precision: high

carl_workers:
  loop:
    algorithm._target_: carl.algorithms.training_loop.TrainingLoopHF
  solver:
    algorithm._target_: carl.algorithms.training_loop.DistributedSolverWorker
  trainer:
    algorithm._target_: carl.algorithms.training_loop.DistributedTrainerWorker


carl_grid:
  # - algorithm.solver.subgoal_generator.generator_k_list: [[6, 4, 2, 1]]
  #   algorithm.solver.planner_class.generators_k_list: [[6, 4, 2, 1]]
  #   algorithm.solver.subgoal_generator.paths_to_generator_weights: [["./rlloop_icml/sokoban/components/n_200/generator/6/checkpoint-4292", "./rlloop_icml/sokoban/components/n_200/generator/4/checkpoint-3327", "./rlloop_icml/sokoban/components/n_200/generator/2/checkpoint-4281", "./rlloop_icml/sokoban/components/n_200/generator/1/checkpoint-4214"]]
  #   algorithm.solver.subgoal_generator.subgoal_generation_kwargs.num_beams: [8]
  #   algorithm.solver.subgoal_generator.subgoal_generation_kwargs.num_return_sequences: [4, 2, 1]
  #   algorithm.instance_generator_batch_size: [1024, 512, 256]
  #   algorithm.solver.validator.cllp.path_to_conditional_low_level_policy_weights: ["./rlloop_icml/sokoban/components/n_200/cllp/6/checkpoint-952"]
  # - algorithm.solver.subgoal_generator.generator_k_list: [[4, 2, 1]]
  #   algorithm.solver.planner_class.generators_k_list: [[4, 2, 1]]
  #   algorithm.solver.subgoal_generator.paths_to_generator_weights: [["./rlloop_icml/sokoban/components/n_200/generator/4/checkpoint-3327", "./rlloop_icml/sokoban/components/n_200/generator/2/checkpoint-4281", "./rlloop_icml/sokoban/components/n_200/generator/1/checkpoint-4214"]]
  #   algorithm.solver.subgoal_generator.subgoal_generation_kwargs.num_beams: [8]
  #   algorithm.solver.subgoal_generator.subgoal_generation_kwargs.num_return_sequences: [4, 2, 1]
  #   algorithm.instance_generator_batch_size: [1024, 512, 256]
  #   algorithm.solver.validator.cllp.path_to_conditional_low_level_policy_weights: ["./rlloop_icml/sokoban/components/n_200/cllp/4/checkpoint-1284"]
  # # [2, 1]
  # - algorithm.solver.subgoal_generator.generator_k_list: [[2, 1]]
  #   algorithm.solver.planner_class.generators_k_list: [[2, 1]]
  #   algorithm.solver.subgoal_generator.paths_to_generator_weights: [["./rlloop_icml/sokoban/components/n_200/generator/2/checkpoint-4281", "./rlloop_icml/sokoban/components/n_200/generator/1/checkpoint-4214"]]
  #   algorithm.solver.subgoal_generator.subgoal_generation_kwargs.num_beams: [8]
  #   algorithm.solver.subgoal_generator.subgoal_generation_kwargs.num_return_sequences: [4, 2, 1]
  #   algorithm.instance_generator_batch_size: [1024, 512, 256]
  #   algorithm.solver.validator.cllp.path_to_conditional_low_level_policy_weights: ["./rlloop_icml/sokoban/components/n_200/cllp/2/checkpoint-1104"]
  # # [1]
  - algorithm.solver.subgoal_generator.generator_k_list: [[1]]
    algorithm.solver.planner_class.generators_k_list: [[1]]
    algorithm.solver.max_nodes: [500]
    algorithm.min_count_of_new_solved_boards_to_next_train_iteration: [10, 50, 100]
    algorithm.solver.subgoal_generator.paths_to_generator_weights: [["./rlloop_icml/sokoban/components/n_200/generator/1/checkpoint-4214"]]
    algorithm.solver.subgoal_generator.subgoal_generation_kwargs.num_beams: [8]
    algorithm.solver.subgoal_generator.subgoal_generation_kwargs.num_return_sequences: [4]
    algorithm.instance_generator_batch_size: [1024]
    algorithm.solver.validator.cllp.path_to_conditional_low_level_policy_weights: ["./rlloop_icml/sokoban/components/n_200/cllp/1/checkpoint-2541"]
    algorithm.solver.subgoal_generator.subgoal_generator_class.training_module.trainer_args.learning_rate: [0.0001] # lr for generator
    algorithm.solver.validator.cllp.training_module.trainer_args.learning_rate: [0.0001]
    algorithm.solver.value_function.training_module.trainer_args.learning_rate: [0.0001]
    algorithm.solver.subgoal_generator.subgoal_generator_class.training_module.trainer_args.weight_decay: [0.000001]
    algorithm.solver.validator.cllp.training_module.trainer_args.weight_decay: [0.0001]
    algorithm.solver.value_function.training_module.trainer_args.weight_decay: [0.0001]
    algorithm.solver.subgoal_generator.subgoal_generator_class.training_module.trainer_args.num_train_epochs: [2]
    algorithm.solver.validator.cllp.training_module.trainer_args.num_train_epochs: [2]
    algorithm.solver.value_function.training_module.trainer_args.num_train_epochs: [2]
  - algorithm.solver.subgoal_generator.generator_k_list: [[1]]
    algorithm.solver.planner_class.generators_k_list: [[1]]
    algorithm.solver.max_nodes: [500]
    algorithm.min_count_of_new_solved_boards_to_next_train_iteration: [10, 50, 100]
    algorithm.solver.subgoal_generator.paths_to_generator_weights: [["./rlloop_icml/sokoban/components/n_200/generator/1/checkpoint-4214"]]
    algorithm.solver.subgoal_generator.subgoal_generation_kwargs.num_beams: [8]
    algorithm.solver.subgoal_generator.subgoal_generation_kwargs.num_return_sequences: [4]
    algorithm.instance_generator_batch_size: [1024]
    algorithm.solver.validator.cllp.path_to_conditional_low_level_policy_weights: ["./rlloop_icml/sokoban/components/n_200/cllp/1/checkpoint-2541"]
    algorithm.solver.subgoal_generator.subgoal_generator_class.training_module.trainer_args.learning_rate: [0.0001] # lr for generator
    algorithm.solver.validator.cllp.training_module.trainer_args.learning_rate: [0.0001]
    algorithm.solver.value_function.training_module.trainer_args.learning_rate: [0.0001]
    algorithm.solver.subgoal_generator.subgoal_generator_class.training_module.trainer_args.weight_decay: [0.000001]
    algorithm.solver.validator.cllp.training_module.trainer_args.weight_decay: [0.0001]
    algorithm.solver.value_function.training_module.trainer_args.weight_decay: [0.0001]
    algorithm.solver.subgoal_generator.subgoal_generator_class.training_module.trainer_args.num_train_epochs: [3]
    algorithm.solver.validator.cllp.training_module.trainer_args.num_train_epochs: [3]
    algorithm.solver.value_function.training_module.trainer_args.num_train_epochs: [3]
  - algorithm.solver.subgoal_generator.generator_k_list: [[1]]
    algorithm.solver.planner_class.generators_k_list: [[1]]
    algorithm.solver.max_nodes: [500]
    algorithm.min_count_of_new_solved_boards_to_next_train_iteration: [100]
    algorithm.solver.subgoal_generator.paths_to_generator_weights: [["./rlloop_icml/sokoban/components/n_200/generator/1/checkpoint-4214"]]
    algorithm.solver.subgoal_generator.subgoal_generation_kwargs.num_beams: [8]
    algorithm.solver.subgoal_generator.subgoal_generation_kwargs.num_return_sequences: [4]
    algorithm.instance_generator_batch_size: [512]
    algorithm.solver.validator.cllp.path_to_conditional_low_level_policy_weights: ["./rlloop_icml/sokoban/components/n_200/cllp/1/checkpoint-2541"]
    algorithm.solver.subgoal_generator.subgoal_generator_class.training_module.trainer_args.learning_rate: [0.00001] # lr for generator
    algorithm.solver.validator.cllp.training_module.trainer_args.learning_rate: [0.00001]
    algorithm.solver.value_function.training_module.trainer_args.learning_rate: [0.00001]
    algorithm.solver.subgoal_generator.subgoal_generator_class.training_module.trainer_args.weight_decay: [0.0000001]
    algorithm.solver.validator.cllp.training_module.trainer_args.weight_decay: [0.00001]
    algorithm.solver.value_function.training_module.trainer_args.weight_decay: [0.00001]
    algorithm.solver.subgoal_generator.subgoal_generator_class.training_module.trainer_args.num_train_epochs: [2]
    algorithm.solver.validator.cllp.training_module.trainer_args.num_train_epochs: [2]
    algorithm.solver.value_function.training_module.trainer_args.num_train_epochs: [2]


# /net/pr2/projects/plgrid/ plggrl_algo/rlloop_icml/
# /net/pr2/projects/plgrid/plggrl_algo/rlloop_icml
# /net/pr2/projects/plgrid/plggrl_algo/rlloop_icml

# /mnt/storage_2/project_data/ grant_619/subsel/rlloop_icml
# /net/pr2/projects/plgrid /plggrl_algo/rlloop_icml
# ./rlloop_icml/sokoban
