algorithm:
  _target_: carl.utils.create_dataset.CreateDataset

  env:
    _target_: carl.environment.gym_rubik.rubik_env.RubikCubeEnv
    tokenizer:
      _target_: carl.environment.gym_rubik.tokenizer.RubikCubeTokenizer
      cut_distance: 20
      type_of_value_training: "regression"

  number_of_trajectories: 500000
  max_moves: 20
  path_to_save: "/net/pr2/projects/plgrid/plggrl_algo/plgmizaw/project_data/rubik/offiline/noise_45_shuffle_20"
  save_after: 50000
  noisy_reverse_prob: None

carl_grid:
  algorithm.noisy_reverse_prob: [0.45]
